"""add available_dates_v2

Revision ID: a2ae93993c6b
Revises: ad9ab0c9340e
Create Date: 2026-06-03 11:50:11.375973
"""
from alembic import op
import sqlalchemy as sa


revision = 'a2ae93993c6b'
down_revision = 'ad9ab0c9340e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('available_dates_v2',
    sa.Column('date_value', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_available_dates_v2_date_value'), 'available_dates_v2', ['date_value'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_available_dates_v2_date_value'), table_name='available_dates_v2')
    op.drop_table('available_dates_v2')
    # ### end Alembic commands ###
