"""Add V2 models

Revision ID: ad9ab0c9340e
Revises: 0002_add_meeting_link
Create Date: 2026-06-03 11:06:58.526343
"""
from alembic import op
import sqlalchemy as sa


revision = 'ad9ab0c9340e'
down_revision = '0002_add_meeting_link'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads_v2',
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'SENT', 'REPLIED', 'BOOKED', 'FAILED', name='lead_status_v2'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('selected_slot', sa.String(length=128), nullable=True),
    sa.Column('booking_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_v2_email'), 'leads_v2', ['email'], unique=True)
    op.create_index(op.f('ix_leads_v2_status'), 'leads_v2', ['status'], unique=False)
    op.create_table('zoho_slots',
    sa.Column('zoho_slot_id', sa.String(length=255), nullable=False),
    sa.Column('slot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'BOOKED', name='slot_status_v2'), nullable=False),
    sa.Column('booked_email', sa.String(length=320), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zoho_slots_slot_time'), 'zoho_slots', ['slot_time'], unique=False)
    op.create_index(op.f('ix_zoho_slots_zoho_slot_id'), 'zoho_slots', ['zoho_slot_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zoho_slots_zoho_slot_id'), table_name='zoho_slots')
    op.drop_index(op.f('ix_zoho_slots_slot_time'), table_name='zoho_slots')
    op.drop_table('zoho_slots')
    op.drop_index(op.f('ix_leads_v2_status'), table_name='leads_v2')
    op.drop_index(op.f('ix_leads_v2_email'), table_name='leads_v2')
    op.drop_table('leads_v2')
    # ### end Alembic commands ###
